version: '3'

services:
  
  exporter:
    image: ruby
    build:
      dockerfile: Dockerfile.exporter
      context: .

  statsd_exporter:
    image: prom/statsd-exporter
    build:
      dockerfile: Dockerfile.statsd_exporter
      context: .
    ports:
    - "9102:9102"
    - "9125:9125/udp"
