FROM ruby

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

WORKDIR /usr/src/app

COPY exporter/Gemfile exporter/Gemfile.lock exporter/exporter.rb ./
RUN bundle install

#COPY exporter/ .

CMD ["/usr/local/bin/ruby", "exporter.rb"]
# CMD ["type", "ruby"]

